<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'slug' => 'dau-tay-da-lat',
                'code' => 'strawberry',
                'name' => 'Dâu tây Đà Lạt',
                'price' => 85000,
                'original_price' => 100000,
                'unit' => 'hộp 500g',
                'origin' => 'Đà Lạt',
                'badge' => 'pb-new',
                'badge_text' => 'Mới',
                'ic' => 'fi-g',
                'bg' => 'bg-g',
                'svg' => '<path d="M12 2C6.48 2 3 6 3 10c0 5.25 9 13 9 13s9-7.75 9-13c0-4-3.48-8-9-8z"/>',
                't1' => 'Nội địa',
                't2' => 'Mới về',
                'desc' => 'Dâu tây tươi ngon, trồng vùng cao Đà Lạt, hái sáng sớm, giao trong ngày. Không dùng thuốc bảo quản.',
                'pack' => 'Hộp 500g',
                'rating_text' => '★★★★★ 4.9 · 128 đánh giá · Đã bán 2.4K',
                'rating_stars' => 5,
                'rating_value' => 4.9,
                'reviews_count' => 128,
                'sold_count' => 2400,
                'nutrition' => 'Mỗi 100g: 32 kcal · Carbs 7.7g · Đường 4.9g · Chất xơ 2g · Vitamin C 58.8mg (98% DV) · Kali 153mg. Tốt cho tim mạch, miễn dịch.',
                'is_daily' => true
            ],
            [
                'slug' => 'xoai-cat-thai',
                'code' => 'mango',
                'name' => 'Xoài cát Thái',
                'price' => 45000,
                'original_price' => null,
                'unit' => 'kg',
                'origin' => 'Thái Lan',
                'badge' => 'pb-hot',
                'badge_text' => 'Hot',
                'ic' => 'fi-o',
                'bg' => 'bg-o',
                'svg' => '<path d="M12 22C6.48 22 3 17 3 13c0-4 3-8 9-11 6 3 9 7 9 11 0 4-3.48 9-9 9z"/>',
                't1' => 'Nhập khẩu',
                't2' => 'Hot',
                'desc' => 'Xoài cát Thái hương thơm, thịt vàng mịn, vị ngọt thanh tự nhiên.',
                'pack' => 'Theo kg',
                'rating_text' => '★★★★★ 4.8 · 96 đánh giá · Đã bán 1.2K',
                'rating_stars' => 5,
                'rating_value' => 4.8,
                'reviews_count' => 96,
                'sold_count' => 1200,
                'nutrition' => 'Mỗi 100g: 60 kcal · Carbs 15g · Đường 13.7g · Chất xơ 1.6g · Vitamin C 36.4mg (60% DV). Tốt cho mắt và hệ tiêu hóa.',
                'is_daily' => true
            ],
            [
                'slug' => 'nho-den-khong-hat',
                'code' => 'grape',
                'name' => 'Nho đen không hạt',
                'price' => 120000,
                'original_price' => 140000,
                'unit' => 'kg',
                'origin' => 'Hoa Kỳ',
                'badge' => 'pb-import',
                'badge_text' => 'Nhập',
                'ic' => 'fi-p',
                'bg' => 'bg-p',
                'svg' => '<circle cx="9" cy="14" r="3"/><circle cx="15" cy="14" r="3"/><circle cx="12" cy="9" r="3"/>',
                't1' => 'Nhập khẩu',
                't2' => 'Premium',
                'desc' => 'Nho đen Mỹ nhập khẩu, không hạt, vỏ mỏng, ngọt lịm mọng nước.',
                'pack' => 'Theo kg',
                'rating_text' => '★★★★☆ 4.7 · 74 đánh giá · Đã bán 850',
                'rating_stars' => 4,
                'rating_value' => 4.7,
                'reviews_count' => 74,
                'sold_count' => 850,
                'nutrition' => 'Mỗi 100g: 69 kcal · Carbs 18g · Đường 15g · Kali 191mg · Vitamin K 14.6mcg (18% DV). Chứa nhiều resveratrol chống oxy hóa.'
            ],
            [
                'slug' => 'cam-navel-uc',
                'code' => 'orange',
                'name' => 'Cam Navel Úc',
                'price' => 65000,
                'original_price' => 80000,
                'unit' => 'kg',
                'origin' => 'Úc',
                'badge' => 'pb-import',
                'badge_text' => 'Nhập',
                'ic' => 'fi-y',
                'bg' => 'bg-y',
                'svg' => '<circle cx="12" cy="12" r="9"/>',
                't1' => 'Nhập khẩu',
                't2' => 'Best Seller',
                'desc' => 'Cam Navel Úc ngọt, ít hạt, múi căng mọng, vỏ cam vàng sáng bóng bẩy.',
                'pack' => 'Theo kg',
                'rating_text' => '★★★★★ 5.0 · 210 đánh giá · Đã bán 3K',
                'rating_stars' => 5,
                'rating_value' => 5.0,
                'reviews_count' => 210,
                'sold_count' => 3000,
                'nutrition' => 'Mỗi 100g: 47 kcal · Vitamin C 53.2mg (89% DV) · Chất xơ 2.4g · Folate 30mcg. Giúp tăng sức đề kháng, đẹp da.',
                'is_daily' => true
            ],
            [
                'slug' => 'kiwi-xanh-nz',
                'code' => 'kiwi',
                'name' => 'Kiwi xanh NZ',
                'price' => 75000,
                'original_price' => null,
                'unit' => '4 trái',
                'origin' => 'New Zealand',
                'badge' => 'pb-import',
                'badge_text' => 'Nhập',
                'ic' => 'fi-g',
                'bg' => 'bg-g',
                'svg' => '<ellipse cx="12" cy="12" rx="10" ry="7"/>',
                't1' => 'Nhập khẩu',
                't2' => 'Tươi',
                'desc' => 'Kiwi xanh New Zealand vỏ nâu nhiều lông tơ, ruột xanh lục bảo, vị chua ngọt đậm đà.',
                'pack' => 'Túi 4 trái',
                'rating_text' => '★★★★★ 4.9 · 88 đánh giá · Đã bán 1.1K',
                'rating_stars' => 5,
                'rating_value' => 4.9,
                'reviews_count' => 88,
                'sold_count' => 1100,
                'nutrition' => 'Mỗi 100g: 61 kcal · Vitamin C 92.7mg (155% DV) · Actinidin enzyme tiêu hóa tốt. Tăng năng lượng, giảm mệt mỏi.'
            ],
            [
                'slug' => 'tao-fuji-my',
                'code' => 'apple',
                'name' => 'Táo Fuji Mỹ',
                'price' => 90000,
                'original_price' => 105000,
                'unit' => 'kg',
                'origin' => 'Hoa Kỳ',
                'badge' => 'pb-import',
                'badge_text' => 'Nhập',
                'ic' => 'fi-r',
                'bg' => 'bg-r',
                'svg' => '<path d="M12 20.94c1.5 0 4-1.44 4-8.94 0-4-2-6-4-6-2 0-4 2-4 6 0 7.5 2.5 8.94 4 8.94z"/>',
                't1' => 'Nhập khẩu',
                't2' => 'Ngon',
                'desc' => 'Táo Fuji Mỹ giòn ngọt, màu đỏ tươi đẹp mắt, chứa nhiều nước và chất xơ.',
                'pack' => 'Theo kg',
                'rating_text' => '★★★★★ 4.8 · 112 đánh giá · Đã bán 1.8K',
                'rating_stars' => 5,
                'rating_value' => 4.8,
                'reviews_count' => 112,
                'sold_count' => 1800,
                'nutrition' => 'Mỗi 100g: 52 kcal · Chất xơ 2.4g (chứa nhiều pectin tốt đường ruột) · Vitamin C 4.6mg. Rất tốt cho người ăn kiêng.'
            ],
            [
                'slug' => 'thanh-long-ruot-do',
                'code' => 'dragon',
                'name' => 'Thanh long ruột đỏ',
                'price' => 35000,
                'original_price' => null,
                'unit' => 'kg',
                'origin' => 'Bình Thuận',
                'badge' => 'pb-new',
                'badge_text' => 'Mới',
                'ic' => 'fi-pk',
                'bg' => 'bg-pk',
                'svg' => '<ellipse cx="12" cy="14" rx="8" ry="6"/>',
                't1' => 'Nội địa',
                't2' => 'Mới về',
                'desc' => 'Thanh long ruột đỏ Bình Thuận ngọt thanh mát, giàu chất xơ, hạt nhỏ dễ tiêu hóa.',
                'pack' => 'Theo kg',
                'rating_text' => '★★★★☆ 4.6 · 63 đánh giá · Đã bán 950',
                'rating_stars' => 4,
                'rating_value' => 4.6,
                'reviews_count' => 63,
                'sold_count' => 950,
                'nutrition' => 'Mỗi 100g: 50 kcal · Giàu Betacyanin chống oxy hóa mạnh mẽ · Vitamin C và Sắt giúp bổ máu, đẹp da.'
            ],
            [
                'slug' => 'gio-qua-tieu-chuan',
                'code' => 'basket1',
                'name' => 'Giỏ quà Tiêu chuẩn',
                'price' => 250000,
                'original_price' => 280000,
                'unit' => 'giỏ',
                'origin' => 'Tổng hợp',
                'badge' => 'pb-special',
                'badge_text' => 'Quà',
                'ic' => 'fi-g',
                'bg' => 'bg-g',
                'svg' => '<path d="M20 12V22H4V12"/><path d="M22 7H2v5h20V7z"/><path d="M12 22V7"/>',
                't1' => 'Giỏ quà',
                't2' => 'Tiêu chuẩn',
                'desc' => 'Giỏ quà bao gồm 5 loại trái cây tươi tuyển chọn nội địa và nhập khẩu, đóng gói thủ công tỉ mỉ kèm nơ.',
                'pack' => '1 giỏ',
                'rating_text' => '★★★★★ 4.9 · 156 đánh giá · Đã bán 1.4K',
                'rating_stars' => 5,
                'rating_value' => 4.9,
                'reviews_count' => 156,
                'sold_count' => 1400,
                'nutrition' => 'Được chọn lọc từ hoa quả tươi hữu cơ, không chất bảo quản, đóng gói vệ sinh an toàn thực phẩm.'
            ],
            [
                'slug' => 'gio-qua-cao-cap',
                'code' => 'basket2',
                'name' => 'Giỏ quà Cao cấp',
                'price' => 450000,
                'original_price' => 500000,
                'unit' => 'giỏ',
                'origin' => 'Nhập khẩu',
                'badge' => 'pb-special',
                'badge_text' => 'VIP',
                'ic' => 'fi-y',
                'bg' => 'bg-y',
                'svg' => '<path d="M20 12V22H4V12"/><path d="M22 7H2v5h20V7z"/><path d="M12 22V7"/>',
                't1' => 'Giỏ quà',
                't2' => 'Cao cấp',
                'desc' => 'Giỏ quà trái cây nhập khẩu 100% (Úc, Mỹ, NZ) sang trọng bậc nhất, thích hợp biếu tặng đối tác, có kèm thiệp chúc mừng theo yêu cầu.',
                'pack' => '1 giỏ',
                'rating_text' => '★★★★★ 5.0 · 98 đánh giá · Đã bán 600',
                'rating_stars' => 5,
                'rating_value' => 5.0,
                'reviews_count' => 98,
                'sold_count' => 600,
                'nutrition' => '100% trái cây nhập khẩu cao cấp đạt chuẩn GlobalGAP, tươi sạch, giàu dưỡng chất lành mạnh.'
            ],
            [
                'slug' => 'chanh-vang-khong-hat',
                'code' => 'lemon',
                'name' => 'Chanh vàng không hạt',
                'price' => 28000,
                'original_price' => 35000,
                'unit' => 'kg',
                'origin' => 'Việt Nam',
                'badge' => 'pb-sale',
                'badge_text' => '–20%',
                'ic' => 'fi-y',
                'bg' => 'bg-y',
                'svg' => '<ellipse cx="12" cy="12" rx="8" ry="6"/>',
                't1' => 'Nội địa',
                't2' => 'Giảm giá',
                'desc' => 'Chanh vàng không hạt giống nhập khẩu trồng nội địa, vỏ vàng óng mượt, vị chua nhẹ rất thơm, nhiều nước.',
                'pack' => 'Theo kg',
                'rating_text' => '★★★★☆ 4.5 · 45 đánh giá · Đã bán 400',
                'rating_stars' => 4,
                'rating_value' => 4.5,
                'reviews_count' => 45,
                'sold_count' => 400,
                'nutrition' => 'Mỗi 100g: 29 kcal · Giàu Vitamin C (53mg) · Axit citric tốt cho tiêu hóa, tăng cường trao đổi chất.'
            ]
        ];

        foreach ($products as $p) {
            Product::create($p);
        }
    }
}
